// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Configure the seed command so `prisma db seed` runs your TypeScript seed file.
    // Use ts-node in CommonJS compilation mode so Node can require() the transpiled module.
    // This avoids the ESM loader cycle errors seen with the ts-node ESM loader.
    seed: 'npx ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts',
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
